/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.jsx'
import { Route as LocationsRouteImport } from './routes/locations.jsx'
import { Route as FleetRouteImport } from './routes/fleet.jsx'
import { Route as ContactRouteImport } from './routes/contact.jsx'
import { Route as AboutRouteImport } from './routes/about.jsx'
import { Route as IndexRouteImport } from './routes/index.jsx'
import { Route as FleetCarIdRouteImport } from './routes/fleet.$carId.jsx'

const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetCarIdRoute = FleetCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => FleetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/locations': typeof LocationsRoute
  '/fleet/$carId': typeof FleetCarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/locations': typeof LocationsRoute
  '/fleet/$carId': typeof FleetCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRouteWithChildren
  '/locations': typeof LocationsRoute
  '/fleet/$carId': typeof FleetCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/fleet'
    | '/locations'
    | '/fleet/$carId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/fleet' | '/locations' | '/fleet/$carId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/fleet'
    | '/locations'
    | '/fleet/$carId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRouteWithChildren
  LocationsRoute: typeof LocationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$carId': {
      id: '/fleet/$carId'
      path: '/$carId'
      fullPath: '/fleet/$carId'
      preLoaderRoute: typeof FleetCarIdRouteImport
      parentRoute: typeof FleetRoute
    }
  }
}

interface FleetRouteChildren {
  FleetCarIdRoute: typeof FleetCarIdRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetCarIdRoute: FleetCarIdRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRouteWithChildren,
  LocationsRoute: LocationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
